services:
  sincronizador-izaias:
    hostname: sincronizador-izaias
    image: sincronizador:latest
    container_name: sincronizador-izaias
    restart: always
    ports:
      - 3334:3000
    environment:
      ENV_DATABASE_SERVER: 161.97.70.96
      ENV_DATABASE_PORT: 33306
      ENV_DATABASE_NAME: NebulaDB_dev
      ENV_DATABASE_USER: usrnebuladev
      ENV_DATABASE_PWD: 8UOVmdRfJajn
      ENV_DATABASE_SSL_MODE: required
      ENV_DATABASE_MAXPOOLSIZE: 75
      ENV_FUSO_HORARIO: -3
      ENV_REDIS_SERVER: redis-dev
      ENV_REDIS_PORT: 6379
      ASPNETCORE_ENVIRONMENT: Development
      ENV_DATABASE_URL: mysql://${ENV_DATABASE_USER:-usrnebuladev}:${ENV_DATABASE_PWD:-NS102030*}@${ENV_DATABASE_SERVER:-mysql-dev}:${ENV_DATABASE_PORT:-3306}/${ENV_DATABASE_NAME:-NebulaDB2_Dev}
      ENV_NOME_IMAGEM: nebulasistemas/nebula-zap-api:dev
      ENV_URL_WHATSAPP: https://whatsappapidev.sistemasnebula.com.br
      ENV_LOCAL_WHATSAPP: -dev
