import { Order } from "../../../../domain/entities/order";
import { Pedidos as PrismaOrder, Prisma } from "@prisma/client";

export class PrismaOrderMapper {
	static toDomain(raw: PrismaOrder): Order {
		return Order.create({
			id: raw.Id,
			storeId: raw.RestauranteId,
			userId: raw.UsuarioId,
			orderTypeId: raw.TipoPedidoId || '',
			addressId: raw.EnderecoId,
			storePaymentMethodId: raw.RestauranteFormaPagamentoId,
			deliveryAreaId: raw.AreaEntregaId,
			orderReviewId: raw.PedidoAvaliacaoId,
			bankTellerId: raw.CaixaId,
			managerId: raw.GerenteId,
			operatorId: raw.OperadorId,
			deviceId: raw.DispositivoId,
			cardId: raw.CartaoId,
			orderNumber: raw.NumPedido,
			createdAt: raw.CriadoEm,
			updatedAt: raw.AlteradoEm,
			deliveryType: raw.TipoEntrega,
			deliveryTime: raw.TempoEntrega,
			status: raw.Status,
			deliveryFee: raw.TaxaEntrega ? raw.TaxaEntrega.toNumber() : null,
			serviceFee: raw.TaxaServico ? raw.TaxaServico.toNumber() : null,
			changeAmount: raw.ValorTroco ? raw.ValorTroco.toNumber() : null,
			discount: raw.Discount ? raw.Discount.toNumber() : null,
			totalAmount: raw.ValorTotal.toNumber(),
			paid: raw.Pago,
			cancellationReason: raw.MotivoCancelamento,
			pixPenseBankHash: raw.HashPixPenseBank,
			alias: raw.Alias,
			canceledAt: raw.CanceladoEm,
			readyAt: raw.ProntoEm,
			completedAt: raw.FinalizouEm,
			delivered: raw.Entregue,
			deliveredAt: raw.EntregueEm,
			observation: raw.Observacao,
			materaReference: raw.MateraReference,
			expiredAt: raw.ExpiradoEm,
			pointsEarned: raw.QuantidadePontuado,
		});
	}

	static toPrisma(order: Order): Prisma.PedidosUncheckedCreateInput {
		return {
			Id: order.id,
			RestauranteId: order.storeId,
			UsuarioId: order.userId,
			TipoPedidoId: order.orderTypeId,
			EnderecoId: order.addressId,
			RestauranteFormaPagamentoId: order.storePaymentMethodId,
			AreaEntregaId: order.deliveryAreaId,
			PedidoAvaliacaoId: order.orderReviewId,
			CaixaId: order.bankTellerId,
			GerenteId: order.managerId,
			OperadorId: order.operatorId,
			DispositivoId: order.deviceId,
			CartaoId: order.cardId,
			NumPedido: order.orderNumber,
			CriadoEm: order.createdAt,
			AlteradoEm: order.updatedAt,
			TipoEntrega: order.deliveryType,
			TempoEntrega: order.deliveryTime,
			Status: order.status,
			TaxaEntrega: order.deliveryFee,
			TaxaServico: order.serviceFee,
			ValorTroco: order.changeAmount,
			Discount: order.discount,
			ValorTotal: order.totalAmount,
			Pago: order.paid,
			MotivoCancelamento: order.cancellationReason,
			HashPixPenseBank: order.pixPenseBankHash,
			Alias: order.alias,
			CanceladoEm: order.canceledAt,
			ProntoEm: order.readyAt,
			FinalizouEm: order.completedAt,
			Entregue: order.delivered,
			EntregueEm: order.deliveredAt,
			Observacao: order.observation,
			MateraReference: order.materaReference,
			ExpiradoEm: order.expiredAt,
			QuantidadePontuado: order.pointsEarned,
		};
	}
}
