import { Restaurant } from "../../src/domain/entities/restaurant";

export function makeRestaurant(override: Partial<Restaurant> = {}): Restaurant {
	const restaurant: Restaurant = {
		Id: "123e4567-e89b-12d3-a456-426614174000",
		Nome: "Baia's Grill",
		ImagemFundo: "https://example.com/imagens/fundo.jpg",
		ImagemLogo: "https://example.com/imagens/logo.png",
		Telefone: "+55 11 91234-5678",
		Parametro_Id: "987e6543-e21b-12d3-a456-426614174000",
		NebulaCode: "123456",
		ChaveAcesso: "123456",
		CriadoEm: new Date(),
		AlteradoEm: null,
		CNPJ: "12.345.678/0001-99",
		MerchantId: "merchant123",
		MerchantPwd: "senhaSecreta",
		TempoMinimo: 30,
		Fechado: false,
		UltimaRequest: new Date(),
		Ativo: true,
		SincronizadoEm: null,
		Facebook: "https://facebook.com/restaurantesaboroso",
		Instagram: "https://instagram.com/restaurantesaboroso",
		Segmento: "Comida Brasileira",
		SoftwareHouse_Id: 1,
		VencimentoLicensa: null,
		VersaoPDVFlow: "1.0.0",
		Email: "contato@saboroso.com",
		Alias: "saboroso",
		VersaoDBPDVFlow: "1.0.0",
		InicioPausaProgramada: null,
		FimPausaProgramada: null,
		Enderecos: [
			{
				Id: "end-001",
				Rua: "Rua das Flores",
				Numero: "123",
				Bairro: "Centro",
				Cidade: "São Paulo",
				Estado: "SP",
				CEP: "01000-000",
				Complemento: "Próximo à praça central",
				CriadoEm: new Date(),
				AlteradoEm: null,
				Ativo: true,
				Latitude: -23.5505199,
				Longitude: -46.6333094,
				Padrao: true,
				Referencia: "Próximo à praça central",
				RestauranteId: "123e4567-e89b-12d3-a456-426614174000",
				UsuarioId: "user-001",
			},
		],
		SoftwareHouse: {
			Id: 1,
			Nome: "Tech Solutions",
			Cnpj: "98.765.432/0001-11",
			Contato: "contato@techsolutions.com",
			CriadoEm: new Date(),
			Ativo: 1,
			Bairro: "Centro",
			Cep: "01000-000",
			Cidade: "São Paulo",
			Complemento: "Próximo à praça central",
			Email: "",
			Estado: "SP",
			IntegratorId: "int-001",
			Logradouro: "Rua das Flores",
			Numero: "123",
			PercentTransactionPixPenseBank: null,
			Telefone: "+55 11 91234-5678",
		},
	};

	return { ...restaurant, ...override };
}
